### ISSUE TITLE
Serverless 0.5.x compatibility

### ISSUE THREAD

**Issue by martinmicunda** [Nopik/serverless-lambda-prune-plugin#9]
This plugin doesn't seem to work with latest serverless v0.5.0.

``` json
/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at Object.posix.join (path.js:479:5)
```

**Comment by hideyuki** [comment]
I fixed this issue and made the pull request https://github.com/Nopik/serverless-lambda-prune-plugin/pull/11

**Comment by jjmartin** [comment]
i think your pull request is in the latest 1.3 version but its still not working for me
